name:                splitcc
version:             0.1.0.0
github:              "githubuser/splitcc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/splitcc#readme>

dependencies:
- base >= 4.7 && < 5
- gauge
- QuickCheck
- split

benchmarks:
  splitcc:
    main: bench/Main.hs
