version: 1.0.{build}

# 日本語環境
init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer

branches:
  only:
    - master
  # blacklist
  except:
    - site

install:
  - cinst haskell-stack
  - cinst ruby
  - gem install rubygems-update --source http://rubygems.org/
  - update_rubygems
  - gem install sass
  - refreshenv                          # 環境変数の再読込

cache:
  - '%LOCALAPPDATA%\Programs\stack\'
  - "C:\\SR"

build_script:
  - cmd: stack build
  - cmd: sass -I sass --scss ./css/main.scss ./css/main.css
  - cmd: stack exec site build