general:
  baseUrl: "https://haskell.e-bigmoon.com"
  headTitle: "BIG MOON"
  siteTitle: "BIG MOON"
  paginate: 7

# Colour (css class, see: http://materializecss.com/color.html)
style:
  headerColour: "indigo lighten-1"
  # MUST in hex format, may the same as header-colour. This colour is for android chrome browser.
  headThemeColour: "#5c6bc0"
  footerColour: "indigo lighten-1"
  footerBtnColour: "indigo lighten-2"
  footerLinkColour: "red-text text-accent-1"
  navbarTextColourDesktop: "white-text"
  navbarTextColourMobile: "waves-effect waves-teal black-text"
  shareButtonColour: "green darken-4"
  shareButtonSmallColour: "green darken-4"

feed:
  title: "BIG MOON"
  description: ""
  authorName: "BIG MOON"
  authorEmail: "it@e-bigmoon.com"
  root: "https://haskell.e-bigmoon.com"
