name: materialize-hakyll
version: '0.1.0.0'
license: AllRightsReserved
dependencies:
- base
- hakyll >= 4.11.0.0 && < 5.0.0.0
- bytestring
- containers
- stm
- mtl
- conduit-combinators
- hakyll-sass
- yaml

executables:
  site:
    main: site.hs
    ghc-options: -threaded
    other-modules: Config