name: materialize-hakyll
version: '0.1.0.0'
license: UnspecifiedLicense
dependencies:
- base ==4.*
- hakyll
- bytestring ==0.10.8.*
- containers
- stm ==2.4.4.*
- mtl ==2.2.*
- conduit-combinators ==1.1.*
- hakyll-sass
- yaml
executables:
  site:
    main: site.hs
    ghc-options: -threaded