name: haskell-blog
version: '0.1.0.0'
license: AllRightsReserved
maintainer: Shinya Yamaguchi
author: Shinya Yamaguchi
description: BIGMOON HASKELLER'S BLOG

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wnoncanonical-monad-instances
- -Wredundant-constraints
- -Wtabs

dependencies:
- base
- blaze-html
- bytestring
- conduit-combinators
- containers
- extensible
- filepath
- hakyll
- lens
- mtl
- stm
- time
- yaml

when:
- condition: "!(os(windows))"
  dependencies:
  - hakyll-sass

executables:
  site:
    source-dirs: app
    main: site.hs
    ghc-options: -threaded
