name: haskell-blog
version: '0.1.0.0'
license: AllRightsReserved
maintainer: Shinya Yamaguchi
author: Shinya Yamaguchi
copyright: 2018 BIG MOON
description: BIGMOON HASKELLERS BLOG

ghc-options:
- -Wall

dependencies:
- base
- hakyll >= 4.11.0.0 && < 5.0.0.0
- bytestring
- containers
- stm
- mtl
- conduit-combinators
- hakyll-sass
- yaml

executables:
  site:
    main: site.hs
    ghc-options: -threaded
    other-modules: Config