# FIXME: stack 1.9.1 が出たら更新する。
# https://circleci.com/gh/e-bigmoon/haskell-blog/1020?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
resolver: lts-12.0
extra-deps:
 - hakyll-sass-0.2.3
flags: {}
extra-package-dbs: []
