resolver: lts-16.1 # ghc-8.8.3
extra-deps:
- extensible-0.8
- file-embed-0.0.11.2
- hakyll-4.13.3.0
- hsass-0.8.0
- hlibsass-0.1.9.0
- github: waddlaw/hakyll-sass
  commit: f4d2e7f003e15f5bfae3cd0f868d574d52e3312a
- membership-0