resolver: lts-17.12 # ghc-8.10.4
extra-deps:
- extensible-0.8.2
- file-embed-0.0.13.0
- hakyll-4.14.0.0
- github: waddlaw/hakyll-sass
  commit: aa3b7b183bd0f68d9d3fc6b280e905d2cd482440
- incremental-0.3.1
- membership-0.0.1