resolver: lts-10.1
extra-deps:
  - hakyll-sass-0.2.3
  - pandoc-citeproc-0.12.2.2
  # [Added -threaded to ghc-options. pthread link errors on linux with GHC 8.2 #601](https://github.com/jaspervdj/hakyll/pull/601)
  - git: https://github.com/waddlaw/hakyll.git
    commit: f1c6a1c6a3ecf58ddae22219ee247c584afee8ef
flags: {}
extra-package-dbs: []
