version: 2

aliases:
  - &default_env
    environment:
      CACHE_KEY: 5
      STACK_VERSION: 2.1.3
  - &create_cache_key_file
    run:
      name: Create cache control key file
      command: echo $CACHE_KEY > cache_key
  - &restore_build_results
    restore_cache:
      keys:
        - stack-{{ checksum "cache_key" }}-{{ checksum "stack.yaml" }}-{{ checksum "bigmoon-haskellers-blog.cabal" }}
        - stack-{{ checksum "cache_key" }}-{{ checksum "stack.yaml" }}-
        - stack-{{ checksum "cache_key" }}-
  - &save_build_results
      save_cache:
        key: stack-{{ checksum "cache_key" }}-{{ checksum "stack.yaml" }}-{{ checksum "bigmoon-haskellers-blog.cabal" }}
        paths:
          - ~/.stack
          - ~/.local/bin
          - .stack-work
  - &restore_preview_results
    restore_cache:
      keys:
        - stack-{{ checksum "cache_key" }}-{{ checksum "./.circleci/preview.hs" }}
        - stack-{{ checksum "cache_key" }}-
  - &save_preview_results
      save_cache:
        key: stack-{{ checksum "cache_key" }}-{{ checksum "./.circleci/preview.hs" }}
        paths:
          - ~/.stack
          - ~/.local/bin
          - .stack-work
  - &display_stack_version
    run:
      name: Display stack version
      command: |
        stack upgrade --binary-version=$STACK_VERSION
        stack --version
  - &install_dependencies:
    run:
      name: Install dependencies
      command: stack test -j 1 --only-dependencies --no-terminal --no-run-tests
      no_output_timeout: 120m

jobs:
  build:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    <<: *default_env
    steps:
      - checkout
      - *create_cache_key_file
      - *restore_build_results
      - *display_stack_version
      - *install_dependencies
      - run:
          name: Run stack test
          command: stack test --fast
      - run:
          name: Generate site files
          command: stack exec site rebuild
      - *save_build_results
      - persist_to_workspace:
          root: .
          paths:
            - ./_site

  pedantic:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    <<: *default_env
    steps:
      - checkout
      - *create_cache_key_file
      - *restore_build_results
      - *display_stack_version
      - *install_dependencies
      - run:
          name: Run stack test --pedantic
          command: |
            stack clean
            stack test --pedantic --fast --no-run-tests

  check:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    steps:
      - checkout
      - run:
          name: Run HLint
          command: |
            curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s -- --version
            curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s app
      # - run:
      #     name: Run stylish-haskell
      #     command: |
      #       curl -sL https://raw.githubusercontent.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s -- -i $(find . -type f -name "*hs" -not -path '.git' -not -path '*.stack-work*')
      #       git --no-pager diff --exit-code

  preview:
    working_directory: ~/haskell-blog
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    <<: *default_env
    steps:
      - checkout
      - *create_cache_key_file
      - *restore_preview_results
      - *display_stack_version
      - attach_workspace:
          at: .
      - store_artifacts:
          path: _site
      - run:
          name: Send Artifacts URL to GitHub when PR
          command: ./.circleci/preview.hs
      - *save_preview_results

  deploy:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    steps:
      - attach_workspace:
          at: .
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git clone --branch=site "https://${GH_TOKEN}@github.com/e-bigmoon/haskell-blog.git"
              cd haskell-blog
              git config user.name "${GIT_NAME}"
              git config user.email "${GIT_EMAIL}"
              cp -r ../_site .
              git add -A
              git commit -m "by Circle CI (build: ${CIRCLE_BUILD_NUM})) : ${CIRCLE_BUILD_URL}"
              git push origin site
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - check
      - preview:
          requires:
            - build
      - pedantic:
          requires:
            - build
      - deploy:
          requires:
            - build
