version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    working_directory: ~/haskell-blog
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - stack-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "stack.yaml" }}-
            - stack-{{ .Environment.COMMON_CACHE_KEY }}-
      - run:
          name: Build docker image
          command: |
            rsync -ave --exclude='.circleci' ./ .circleci/code
            docker-compose -f .circleci/docker-compose.yml build --build-arg resolver=$(cat stack.yaml | sed -n '/resolver:/p' | sed -r 's/resolver:\s(.*)/\1/') app
      - save_cache:
          key: stack-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - .circleci/code/.stack-work
      - restore_cache:
          keys:
            - stack-{{ .Environment.COMMON_CACHE_KEY_SCRIPT }}-{{ checksum "./.circleci/preview.hs" }}
            - stack-{{ .Environment.COMMON_CACHE_KEY_SCRIPT }}-
      - run:
          name: build
          command: |
            curl -sSL https://get.haskellstack.org/ | sh -s - -f
            stack build
            stack exec site rebuild
      - run:
          name: Run stack test
          command: stack --no-terminal test
      - run:
          name: Run stack test --pedantic
          command: |
            stack clean
            stack --no-terminal test --pedantic
      - run:
          name: Run HLint
          command: |
            curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s -- --version
            curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
      - run:
          name: Run stack exec site rebuild
          command: stack exec site rebuild
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git clone --branch=site git@github.com:e-bigmoon/haskell-blog.git
              cd haskell-blog
              cp -r ../_site/ .
              git add -A
              git commit -m "by Circle CI (build: ${CIRCLE_BUILD_NUM})) : ${CIRCLE_BUILD_URL}"
              git push origin site
            fi
      - store_artifacts:
          path: _site
      - run:
          name: Send Artifacts URL to GitHub when PR
          command: ./.circleci/preview.hs
      - save_cache:
          key: stack-{{ .Environment.COMMON_CACHE_KEY_SCRIPT }}-{{ checksum "./.circleci/preview.hs" }}
          paths:
            - /home/circleci/.stack/
            - /home/circleci/.local/bin/
