version: '2'
services:
  app:
    build:
      context: ./
      args:
        - stack_version=1.6.5
    command: tail -f /dev/null
    volumes:
      - ./code:/opt/server/
    working_dir: /opt/server
    tty: true