name: adding-a-new-monad-transformer1
dependencies:
- base >= 4.7 && < 5
- base16-bytestring
- exceptions
- crypto-api
- monadcryptorandom
- monad-logger
- mtl
- persistent-sqlite
- resourcet
- text
- time
- unliftio
- yesod
- yesod-core
- transformers
executables:
  ex1:
    main: Main.hs
