name: authentificateMe
dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- data-default
- blaze-html
- persistent-sqlite
- http-client-tls
- http-conduit
- load-env
- mime-mail
- monad-logger
- persistent-template
- shakespeare
- text
- time
- yesod
- yesod-auth
- yesod-auth-oauth2
- warp
executables:
  authentificateMe:
    main: Main.hs
