name: cabal-fmt

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  format:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.6.5"
        cabal-version: "3.0"

    - name: Cache ~/.cabal/bin
      id: cache-bin
      uses: actions/cache@v1.0.3
      with:
        path: ~/.cabal/bin
        key: v1-cabal-fmt-v0.1.2
        restore-keys: |
          v1-cabal-fmt-

    - name: Install cabal-fmt
      if: steps.cache-bin.outputs.cache-hit != 'true'
      run: |
        cabal v2-update
        cabal v2-install cabal-fmt --overwrite-policy=always

    - name: Apply cabal-fmt
      run: |
        export PATH=~/.cabal/bin/:$PATH
        cabal-fmt -i bigmoon-haskellers-blog.cabal
        git --no-pager diff --exit-code