name: cabal

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
        ghc: ["8.8.2"]
        cabal: ["3.0"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1.1.2
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-v5-cabal-store

    - name: Cache dist-newstyle
      uses: actions/cache@v1.1.2
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-v5-cabal-dist

    - name: Install dependencies
      run: |
        cabal update
        cabal configure --disable-optimization --write-ghc-environment-files=always -j2
        cabal build all --only-dependencies

    - name: Build
      run: cabal build