name: cabal

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.6.5"]
        cabal: ["3.0"]

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Display ghc & cabal version
      run: |
        ghc -V
        cabal -V

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1.1.0
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-v2-cabal-store

    - name: Cache dist-newstyle
      uses: actions/cache@v1.1.0
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-v2-haskell-blog-dist

    - name: Install dependencies
      run: |
        cabal update
        cabal configure --disable-optimization --write-ghc-environment-files=always -j2
        cabal build all --only-dependencies

    - name: Build
      run: cabal build