name: deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: "00 15 * * *"

jobs:
  netlify:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cache-version: ["2020-03-16"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.8.3"
        cabal-version: "3.0"

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cache-version }}-cabal-store

    - name: Build
      run: |
        cabal update
        cabal configure -j2
        cabal run site build

    - name: Commit files
      run: |
        git config --local user.email "bot@e-bigmoon.com"
        git config --local user.name "BOT MOON"

        git fetch

        mv _site _site_latest
        git checkout site
        rm -rf _site
        mv _site_latest _site

        if [ "`git status -s | wc -l`" -gt 0 ]; then
          git add _site
          git commit -m "by Github Action"
        fi
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN_DEPLOY }}
        branch: "site"