name: format

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cache-version: ["2020-05-30"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: "8.8.3"
        cabal-version: "3.2.0.0"

    - uses: v2.0
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.cache-version }}-cabal

    - name: Install cabal-fmt, ormolu
      run: |
        cabal update
        cabal install cabal-fmt ormolu --overwrite-policy=always --install-method=copy -j2 -z

    - name: Apply cabal-fmt
      run: |
        export PATH=~/.cabal/bin/:$PATH
        cabal-fmt -i *.cabal
        git --no-pager diff --exit-code

    - name: Apply ormolu
      run: |
        export PATH=~/.cabal/bin/:$PATH
        ormolu -o -XTypeApplications --mode inplace $(find app -type f -name "*.hs")
        git --no-pager diff --exit-code