name: nightly

on:
  schedule:
    - cron: "00 15 * * *"
  pull_request:
    branches:
      - '*'

jobs:
  cabal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: "8.10.1"
        cabal-version: "3.2.0.0"

    - name: Install dependencies & build
      run: |
        cabal update --index-state=HEAD
        cabal build --project=cabal-nightly.project

  stack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # windows-2019 は pandoc の問題によりブロック
        # https://github.com/jgm/pandoc/commit/9feefa39319358acc84811e6017aeea60f9140c3
        os: [ubuntu-18.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: "8.10.1"
        stack-version: "2.3.1"
        enable-stack: true

    - name: Install dependencies
      run: |
        # echo -e "\nallow-newer: true" >> stack.yaml
        stack test --resolver=nightly --only-dependencies --stack-yaml=stack-nightly.yaml

    - name: Build
      run: |
        stack test --fast --resolver=nightly --stack-yaml=stack-nightly.yaml
        stack install --fast --resolver=nightly --stack-yaml=stack-nightly.yaml
