name: nightly

on:
  schedule:
    - cron: "00 15 * * *"

jobs:
  cabal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15] #windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.10.1"
        cabal-version: "3.2.0.0"

    - name: Install dependencies & build
      run: |
        echo ::add-path::C:\msys64\usr\bin\
        cabal update --index-state=HEAD
        cabal build --project=cabal-nightly.project

  stack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15] # windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.10.1"
        stack-version: "2.3.1"
        enable-stack: true

    - name: Install dependencies
      run: |
        echo ::add-path::C:\msys64\usr\bin\
        stack test --resolver=nightly --only-dependencies
      env:
        STACK_YAML: stack-nightly.yaml

    - name: Build
      run: |
        stack test --fast --resolver=nightly
        stack install --fast --resolver=nightly
      env:
        STACK_YAML: stack-nightly.yaml
