name: 'nightly dependencies check'

# on:
#   schedule:
#     - cron: "00 15 * * *"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: waddlaw/cabal-outdated-action@main