name: 'dependencies check'

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "00 15 * * *"

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: waddlaw/cabal-outdated-action@main