name: stack

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        ghc: ["8.8"]
        stack: ["2.5.1"]
        cache-version: ["2020-11-20"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - name: Cache ~/.stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.stack }}-${{ matrix.cache-version }}-stack

    - name: Install dependencies
      run: stack test --only-dependencies --system-ghc

    - name: Build
      run: |
        stack test --fast --system-ghc
        stack install --fast --system-ghc
